"""
    Sendbird Platform SDK

    Sendbird Platform API SDK  https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: support@sendbird.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import sendbird_platform_sdk
from sendbird_platform_sdk.model.send_bird_bots_message_response_message_extended_message_payload import SendBirdBotsMessageResponseMessageExtendedMessagePayload


class TestSendBirdBotsMessageResponseMessageExtendedMessagePayload(unittest.TestCase):
    """SendBirdBotsMessageResponseMessageExtendedMessagePayload unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSendBirdBotsMessageResponseMessageExtendedMessagePayload(self):
        """Test SendBirdBotsMessageResponseMessageExtendedMessagePayload"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SendBirdBotsMessageResponseMessageExtendedMessagePayload()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
