"""
    Sendbird Platform SDK

    Sendbird Platform API Javascript SDK  https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import sendbird_platform_sdk
from sendbird_platform_sdk.model.get_statistics_daily_response_statistics import GetStatisticsDailyResponseStatistics
globals()['GetStatisticsDailyResponseStatistics'] = GetStatisticsDailyResponseStatistics
from sendbird_platform_sdk.model.get_statistics_monthly_response import GetStatisticsMonthlyResponse


class TestGetStatisticsMonthlyResponse(unittest.TestCase):
    """GetStatisticsMonthlyResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetStatisticsMonthlyResponse(self):
        """Test GetStatisticsMonthlyResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetStatisticsMonthlyResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
