"""
    Sendbird Platform SDK

    Sendbird Platform API Javascript SDK  https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import sendbird_platform_sdk
from sendbird_platform_sdk.model.inline_response20063_file import InlineResponse20063File


class TestInlineResponse20063File(unittest.TestCase):
    """InlineResponse20063File unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20063File(self):
        """Test InlineResponse20063File"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InlineResponse20063File()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
