"""
    Sendbird Platform SDK

    Sendbird Platform API Javascript SDK  https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import sendbird_platform_sdk
from sendbird_platform_sdk.model.list_push_configurations_response_push_configurations_inner import ListPushConfigurationsResponsePushConfigurationsInner


class TestListPushConfigurationsResponsePushConfigurationsInner(unittest.TestCase):
    """ListPushConfigurationsResponsePushConfigurationsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testListPushConfigurationsResponsePushConfigurationsInner(self):
        """Test ListPushConfigurationsResponsePushConfigurationsInner"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ListPushConfigurationsResponsePushConfigurationsInner()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
