"""
    Sendbird Platform SDK

    Sendbird Platform API Javascript SDK  https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import sendbird_platform_sdk
from sendbird_platform_sdk.api.open_channel_api import OpenChannelApi  # noqa: E501


class TestOpenChannelApi(unittest.TestCase):
    """OpenChannelApi unit test stubs"""

    def setUp(self):
        self.api = OpenChannelApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_oc_ban_user(self):
        """Test case for oc_ban_user

        Ban a user  # noqa: E501
        """
        pass

    def test_oc_cancel_the_registration_of_operators(self):
        """Test case for oc_cancel_the_registration_of_operators

        Cancel the registration of operators  # noqa: E501
        """
        pass

    def test_oc_create_channel(self):
        """Test case for oc_create_channel

        Create a channel  # noqa: E501
        """
        pass

    def test_oc_delete_channel_by_url(self):
        """Test case for oc_delete_channel_by_url

        Delete a channel  # noqa: E501
        """
        pass

    def test_oc_freeze_channel(self):
        """Test case for oc_freeze_channel

        Freeze a channel  # noqa: E501
        """
        pass

    def test_oc_list_banned_users(self):
        """Test case for oc_list_banned_users

        List banned users  # noqa: E501
        """
        pass

    def test_oc_list_channels(self):
        """Test case for oc_list_channels

        List channels  # noqa: E501
        """
        pass

    def test_oc_list_muted_users(self):
        """Test case for oc_list_muted_users

        List muted users  # noqa: E501
        """
        pass

    def test_oc_list_operators(self):
        """Test case for oc_list_operators

        List operators  # noqa: E501
        """
        pass

    def test_oc_list_participants(self):
        """Test case for oc_list_participants

        List participants  # noqa: E501
        """
        pass

    def test_oc_mute_user(self):
        """Test case for oc_mute_user

        Mute a user  # noqa: E501
        """
        pass

    def test_oc_register_operators(self):
        """Test case for oc_register_operators

        Register operators  # noqa: E501
        """
        pass

    def test_oc_unban_user_by_id(self):
        """Test case for oc_unban_user_by_id

        Unban a user  # noqa: E501
        """
        pass

    def test_oc_unmute_user_by_id(self):
        """Test case for oc_unmute_user_by_id

        Unmute a user  # noqa: E501
        """
        pass

    def test_oc_update_ban_by_id(self):
        """Test case for oc_update_ban_by_id

        Update a ban  # noqa: E501
        """
        pass

    def test_oc_update_channel_by_url(self):
        """Test case for oc_update_channel_by_url

        Update a channel  # noqa: E501
        """
        pass

    def test_oc_view_ban_by_id(self):
        """Test case for oc_view_ban_by_id

        View a ban  # noqa: E501
        """
        pass

    def test_oc_view_channel_by_url(self):
        """Test case for oc_view_channel_by_url

        View a channel  # noqa: E501
        """
        pass

    def test_oc_view_mute_by_id(self):
        """Test case for oc_view_mute_by_id

        View a mute  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
