"""
    Sendbird Platform SDK

    Sendbird Platform API SDK  https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: support@sendbird.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import sendbird_platform_sdk
from sendbird_platform_sdk.model.set_domain_filter_data_domain_filter import SetDomainFilterDataDomainFilter
from sendbird_platform_sdk.model.set_domain_filter_data_image_moderation import SetDomainFilterDataImageModeration
from sendbird_platform_sdk.model.set_domain_filter_data_profanity_filter import SetDomainFilterDataProfanityFilter
from sendbird_platform_sdk.model.set_domain_filter_data_profanity_triggered_moderation import SetDomainFilterDataProfanityTriggeredModeration
globals()['SetDomainFilterDataDomainFilter'] = SetDomainFilterDataDomainFilter
globals()['SetDomainFilterDataImageModeration'] = SetDomainFilterDataImageModeration
globals()['SetDomainFilterDataProfanityFilter'] = SetDomainFilterDataProfanityFilter
globals()['SetDomainFilterDataProfanityTriggeredModeration'] = SetDomainFilterDataProfanityTriggeredModeration
from sendbird_platform_sdk.model.set_domain_filter_data import SetDomainFilterData


class TestSetDomainFilterData(unittest.TestCase):
    """SetDomainFilterData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSetDomainFilterData(self):
        """Test SetDomainFilterData"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SetDomainFilterData()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
