"""
    Sendbird Platform SDK

    Sendbird Platform API Javascript SDK  https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import sendbird_platform_sdk
from sendbird_platform_sdk.model.send_bird_thumbnail_object import SendBirdThumbnailObject


class TestSendBirdThumbnailObject(unittest.TestCase):
    """SendBirdThumbnailObject unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSendBirdThumbnailObject(self):
        """Test SendBirdThumbnailObject"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SendBirdThumbnailObject()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
