"""
    Sendbird Platform SDK

    Sendbird Platform API Javascript SDK  https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import sendbird_platform_sdk
from sendbird_platform_sdk.api.advanced_analytics_api import AdvancedAnalyticsApi  # noqa: E501


class TestAdvancedAnalyticsApi(unittest.TestCase):
    """AdvancedAnalyticsApi unit test stubs"""

    def setUp(self):
        self.api = AdvancedAnalyticsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_retrieve_advanced_analytics_metrics(self):
        """Test case for retrieve_advanced_analytics_metrics

        Retrieve Advanced analytics metrics  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
