"""
    Sendbird Platform SDK

    Sendbird Platform API SDK  https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: support@sendbird.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import sendbird_platform_sdk
from sendbird_platform_sdk.model.gc_typing_indicators_data import GcTypingIndicatorsData


class TestGcTypingIndicatorsData(unittest.TestCase):
    """GcTypingIndicatorsData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGcTypingIndicatorsData(self):
        """Test GcTypingIndicatorsData"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GcTypingIndicatorsData()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
