"""
    Sendbird Platform SDK

    Sendbird Platform API Javascript SDK  https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import sendbird_platform_sdk
from sendbird_platform_sdk.api.bot_api import BotApi  # noqa: E501


class TestBotApi(unittest.TestCase):
    """BotApi unit test stubs"""

    def setUp(self):
        self.api = BotApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_bot(self):
        """Test case for create_bot

        Create a bot  # noqa: E501
        """
        pass

    def test_delete_bot_by_id(self):
        """Test case for delete_bot_by_id

        Delete a bot  # noqa: E501
        """
        pass

    def test_join_channels(self):
        """Test case for join_channels

        Join channels  # noqa: E501
        """
        pass

    def test_leave_channels(self):
        """Test case for leave_channels

        Leave channels - When leaving all channels  # noqa: E501
        """
        pass

    def test_leave_channels_by_url(self):
        """Test case for leave_channels_by_url

        Leave channels - When leaving a channel by its channel URL  # noqa: E501
        """
        pass

    def test_list_bots(self):
        """Test case for list_bots

        List bots  # noqa: E501
        """
        pass

    def test_send_bots_message(self):
        """Test case for send_bots_message

        Send a bot's message  # noqa: E501
        """
        pass

    def test_update_bot_by_id(self):
        """Test case for update_bot_by_id

        Update a bot  # noqa: E501
        """
        pass

    def test_view_bot_by_id(self):
        """Test case for view_bot_by_id

        View a bot  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
