"""
    Sendbird Platform SDK

    Sendbird Platform API Javascript SDK  https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import sendbird_platform_sdk
from sendbird_platform_sdk.model.get_detailed_open_status_of_announcement_by_id_response_open_status_inner import GetDetailedOpenStatusOfAnnouncementByIdResponseOpenStatusInner


class TestGetDetailedOpenStatusOfAnnouncementByIdResponseOpenStatusInner(unittest.TestCase):
    """GetDetailedOpenStatusOfAnnouncementByIdResponseOpenStatusInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetDetailedOpenStatusOfAnnouncementByIdResponseOpenStatusInner(self):
        """Test GetDetailedOpenStatusOfAnnouncementByIdResponseOpenStatusInner"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetDetailedOpenStatusOfAnnouncementByIdResponseOpenStatusInner()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
