"""
    Sendbird Platform SDK

    Sendbird Platform API SDK  https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: support@sendbird.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import sendbird_platform_sdk
from sendbird_platform_sdk.model.set_domain_filter_data_profanity_filter_regex_filters_inner import SetDomainFilterDataProfanityFilterRegexFiltersInner
globals()['SetDomainFilterDataProfanityFilterRegexFiltersInner'] = SetDomainFilterDataProfanityFilterRegexFiltersInner
from sendbird_platform_sdk.model.set_domain_filter_data_profanity_filter import SetDomainFilterDataProfanityFilter


class TestSetDomainFilterDataProfanityFilter(unittest.TestCase):
    """SetDomainFilterDataProfanityFilter unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSetDomainFilterDataProfanityFilter(self):
        """Test SetDomainFilterDataProfanityFilter"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SetDomainFilterDataProfanityFilter()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
