"""
    Sendbird Platform SDK

    Sendbird Platform API SDK  https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: support@sendbird.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import sendbird_platform_sdk
from sendbird_platform_sdk.model.send_bird_user import SendBirdUser
globals()['SendBirdUser'] = SendBirdUser
from sendbird_platform_sdk.model.list_muted_users_in_channels_with_custom_channel_type200_response import ListMutedUsersInChannelsWithCustomChannelType200Response


class TestListMutedUsersInChannelsWithCustomChannelType200Response(unittest.TestCase):
    """ListMutedUsersInChannelsWithCustomChannelType200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testListMutedUsersInChannelsWithCustomChannelType200Response(self):
        """Test ListMutedUsersInChannelsWithCustomChannelType200Response"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ListMutedUsersInChannelsWithCustomChannelType200Response()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
