"""
    Sendbird Platform SDK

    Sendbird Platform API SDK  [https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api](https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api)  Contact Support:   Name: Sendbird   Email: [support@sendbird.com](https://mailto:support@sendbird.com)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: support@sendbird.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import sendbird_platform_sdk
from sendbird_platform_sdk.model.sendbird_basic_user_info import SendbirdBasicUserInfo
from sendbird_platform_sdk.model.sendbird_disappearing_message import SendbirdDisappearingMessage
from sendbird_platform_sdk.model.sendbird_group_channel_detail_channel import SendbirdGroupChannelDetailChannel
from sendbird_platform_sdk.model.sendbird_member import SendbirdMember
from sendbird_platform_sdk.model.sendbird_message_response import SendbirdMessageResponse
from sendbird_platform_sdk.model.sendbird_sms_fallback import SendbirdSmsFallback
from sendbird_platform_sdk.model.sendbird_user import SendbirdUser
globals()['SendbirdBasicUserInfo'] = SendbirdBasicUserInfo
globals()['SendbirdDisappearingMessage'] = SendbirdDisappearingMessage
globals()['SendbirdGroupChannelDetailChannel'] = SendbirdGroupChannelDetailChannel
globals()['SendbirdMember'] = SendbirdMember
globals()['SendbirdMessageResponse'] = SendbirdMessageResponse
globals()['SendbirdSmsFallback'] = SendbirdSmsFallback
globals()['SendbirdUser'] = SendbirdUser
from sendbird_platform_sdk.model.sendbird_group_channel_detail import SendbirdGroupChannelDetail


class TestSendbirdGroupChannelDetail(unittest.TestCase):
    """SendbirdGroupChannelDetail unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSendbirdGroupChannelDetail(self):
        """Test SendbirdGroupChannelDetail"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SendbirdGroupChannelDetail()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
