"""
    Sendbird Platform SDK

    Sendbird Platform API Javascript SDK  https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import sendbird_platform_sdk
from sendbird_platform_sdk.model.revoke_secondary_api_token_by_token_response import RevokeSecondaryApiTokenByTokenResponse


class TestRevokeSecondaryApiTokenByTokenResponse(unittest.TestCase):
    """RevokeSecondaryApiTokenByTokenResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRevokeSecondaryApiTokenByTokenResponse(self):
        """Test RevokeSecondaryApiTokenByTokenResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RevokeSecondaryApiTokenByTokenResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
