"""
    Sendbird Platform SDK

    Sendbird Platform API Javascript SDK  https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import sendbird_platform_sdk
from sendbird_platform_sdk.model.update_count_preference_of_channel_by_url_response import UpdateCountPreferenceOfChannelByUrlResponse


class TestUpdateCountPreferenceOfChannelByUrlResponse(unittest.TestCase):
    """UpdateCountPreferenceOfChannelByUrlResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUpdateCountPreferenceOfChannelByUrlResponse(self):
        """Test UpdateCountPreferenceOfChannelByUrlResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UpdateCountPreferenceOfChannelByUrlResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
