"""
    Sendbird Platform SDK

    Sendbird Platform API Javascript SDK  https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import sendbird_platform_sdk
from sendbird_platform_sdk.model.schedule_announcement_data import ScheduleAnnouncementData


class TestScheduleAnnouncementData(unittest.TestCase):
    """ScheduleAnnouncementData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testScheduleAnnouncementData(self):
        """Test ScheduleAnnouncementData"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ScheduleAnnouncementData()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
