"""
    Sendbird Platform SDK

    Sendbird Platform API Javascript SDK  https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import sendbird_platform_sdk
from sendbird_platform_sdk.model.list_all_emojis_and_emoji_categories_response_emoji_categories_inner import ListAllEmojisAndEmojiCategoriesResponseEmojiCategoriesInner
globals()['ListAllEmojisAndEmojiCategoriesResponseEmojiCategoriesInner'] = ListAllEmojisAndEmojiCategoriesResponseEmojiCategoriesInner
from sendbird_platform_sdk.model.list_all_emojis_and_emoji_categories_response import ListAllEmojisAndEmojiCategoriesResponse


class TestListAllEmojisAndEmojiCategoriesResponse(unittest.TestCase):
    """ListAllEmojisAndEmojiCategoriesResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testListAllEmojisAndEmojiCategoriesResponse(self):
        """Test ListAllEmojisAndEmojiCategoriesResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ListAllEmojisAndEmojiCategoriesResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
