"""
    Sendbird Platform SDK

    Sendbird Platform API Javascript SDK  https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import sendbird_platform_sdk
from sendbird_platform_sdk.model.send_bird_channel_response import SendBirdChannelResponse
globals()['SendBirdChannelResponse'] = SendBirdChannelResponse
from sendbird_platform_sdk.model.inline_response20023 import InlineResponse20023


class TestInlineResponse20023(unittest.TestCase):
    """InlineResponse20023 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20023(self):
        """Test InlineResponse20023"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InlineResponse20023()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
