"""
    Sendbird Platform SDK

    Sendbird Platform API Javascript SDK  https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import sendbird_platform_sdk
from sendbird_platform_sdk.model.inline_response20047_og_tag_og_image import InlineResponse20047OgTagOgImage
globals()['InlineResponse20047OgTagOgImage'] = InlineResponse20047OgTagOgImage
from sendbird_platform_sdk.model.inline_response20047_og_tag import InlineResponse20047OgTag


class TestInlineResponse20047OgTag(unittest.TestCase):
    """InlineResponse20047OgTag unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20047OgTag(self):
        """Test InlineResponse20047OgTag"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InlineResponse20047OgTag()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
