"""
    Sendbird Platform SDK

    Sendbird Platform API Javascript SDK  https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import sendbird_platform_sdk
from sendbird_platform_sdk.model.send_bird_channel_response import SendBirdChannelResponse
from sendbird_platform_sdk.model.send_bird_message_response import SendBirdMessageResponse
from sendbird_platform_sdk.model.send_bird_user import SendBirdUser
globals()['SendBirdChannelResponse'] = SendBirdChannelResponse
globals()['SendBirdMessageResponse'] = SendBirdMessageResponse
globals()['SendBirdUser'] = SendBirdUser
from sendbird_platform_sdk.model.list_reports_on_message_by_id_response_report_logs import ListReportsOnMessageByIdResponseReportLogs


class TestListReportsOnMessageByIdResponseReportLogs(unittest.TestCase):
    """ListReportsOnMessageByIdResponseReportLogs unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testListReportsOnMessageByIdResponseReportLogs(self):
        """Test ListReportsOnMessageByIdResponseReportLogs"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ListReportsOnMessageByIdResponseReportLogs()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
