"""
    Sendbird Platform SDK

    Sendbird Platform API SDK  [https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api](https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api)  Contact Support:   Name: Sendbird   Email: [support@sendbird.com](https://mailto:support@sendbird.com)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: support@sendbird.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import sendbird_platform_sdk
from sendbird_platform_sdk.model.send_text_message_request_body_push_message_template import SendTextMessageRequestBodyPushMessageTemplate
from sendbird_platform_sdk.model.sendbird_sorted_metaarray import SendbirdSortedMetaarray
globals()['SendTextMessageRequestBodyPushMessageTemplate'] = SendTextMessageRequestBodyPushMessageTemplate
globals()['SendbirdSortedMetaarray'] = SendbirdSortedMetaarray
from sendbird_platform_sdk.model.send_text_message_request_body import SendTextMessageRequestBody


class TestSendTextMessageRequestBody(unittest.TestCase):
    """SendTextMessageRequestBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSendTextMessageRequestBody(self):
        """Test SendTextMessageRequestBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SendTextMessageRequestBody()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
