"""
    Sendbird Platform SDK

    Sendbird Platform API SDK  [https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api](https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api)  Contact Support:   Name: Sendbird   Email: [support@sendbird.com](https://mailto:support@sendbird.com)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: support@sendbird.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import sendbird_platform_sdk
from sendbird_platform_sdk.model.update_bot_by_id_data import UpdateBotByIdData


class TestUpdateBotByIdData(unittest.TestCase):
    """UpdateBotByIdData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUpdateBotByIdData(self):
        """Test UpdateBotByIdData"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UpdateBotByIdData()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
