"""
    Sendbird Platform SDK

    Sendbird Platform API SDK  https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: support@sendbird.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import sendbird_platform_sdk
from sendbird_platform_sdk.model.view_number_of_channels_by_join_status_response import ViewNumberOfChannelsByJoinStatusResponse


class TestViewNumberOfChannelsByJoinStatusResponse(unittest.TestCase):
    """ViewNumberOfChannelsByJoinStatusResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testViewNumberOfChannelsByJoinStatusResponse(self):
        """Test ViewNumberOfChannelsByJoinStatusResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ViewNumberOfChannelsByJoinStatusResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
