"""
    Sendbird Platform SDK

    Sendbird Platform API SDK  [https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api](https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api)  Contact Support:   Name: Sendbird   Email: [support@sendbird.com](https://mailto:support@sendbird.com)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: support@sendbird.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import sendbird_platform_sdk
from sendbird_platform_sdk.model.send_a_message_request_push_message_template_one_of import SendAMessageRequestPushMessageTemplateOneOf


class TestSendAMessageRequestPushMessageTemplateOneOf(unittest.TestCase):
    """SendAMessageRequestPushMessageTemplateOneOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSendAMessageRequestPushMessageTemplateOneOf(self):
        """Test SendAMessageRequestPushMessageTemplateOneOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SendAMessageRequestPushMessageTemplateOneOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
