"""
    Sendbird Platform SDK

    Sendbird Platform API Javascript SDK  https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import sendbird_platform_sdk
from sendbird_platform_sdk.model.inline_response20014 import InlineResponse20014


class TestInlineResponse20014(unittest.TestCase):
    """InlineResponse20014 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20014(self):
        """Test InlineResponse20014"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InlineResponse20014()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
