"""
    Sendbird Platform SDK

    Sendbird Platform API Javascript SDK  https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import sendbird_platform_sdk
from sendbird_platform_sdk.model.enable_reactions_response import EnableReactionsResponse


class TestEnableReactionsResponse(unittest.TestCase):
    """EnableReactionsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEnableReactionsResponse(self):
        """Test EnableReactionsResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = EnableReactionsResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
