"""
    Sendbird Platform SDK

    Sendbird Platform API SDK  https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: support@sendbird.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import sendbird_platform_sdk
from sendbird_platform_sdk.model.send_bird_group_channel_disappearing_message import SendBirdGroupChannelDisappearingMessage


class TestSendBirdGroupChannelDisappearingMessage(unittest.TestCase):
    """SendBirdGroupChannelDisappearingMessage unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSendBirdGroupChannelDisappearingMessage(self):
        """Test SendBirdGroupChannelDisappearingMessage"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SendBirdGroupChannelDisappearingMessage()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
