"""
    Sendbird Platform SDK

    Sendbird Platform API Javascript SDK  https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import sendbird_platform_sdk
from sendbird_platform_sdk.model.blob import Blob
from sendbird_platform_sdk.model.send_bird_apple_critical_alert_options import SendBirdAppleCriticalAlertOptions
from sendbird_platform_sdk.model.send_bird_message_meta_array import SendBirdMessageMetaArray
from sendbird_platform_sdk.model.send_bird_thumbnail_size import SendBirdThumbnailSize
from sendbird_platform_sdk.model.send_bird_user import SendBirdUser
globals()['Blob'] = Blob
globals()['SendBirdAppleCriticalAlertOptions'] = SendBirdAppleCriticalAlertOptions
globals()['SendBirdMessageMetaArray'] = SendBirdMessageMetaArray
globals()['SendBirdThumbnailSize'] = SendBirdThumbnailSize
globals()['SendBirdUser'] = SendBirdUser
from sendbird_platform_sdk.model.send_bird_file_message_params import SendBirdFileMessageParams


class TestSendBirdFileMessageParams(unittest.TestCase):
    """SendBirdFileMessageParams unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSendBirdFileMessageParams(self):
        """Test SendBirdFileMessageParams"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SendBirdFileMessageParams()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
